// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package gateway

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Success Status = 0
	Status_Refused Status = 1
	Status_Timeout Status = 2
)

var Status_name = map[int32]string{
	0: "Success",
	1: "Refused",
	2: "Timeout",
}

var Status_value = map[string]int32{
	"Success": 0,
	"Refused": 1,
	"Timeout": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type ReportRequest struct {
	LoginId              string   `protobuf:"bytes,1,opt,name=loginId,proto3" json:"loginId,omitempty"`
	ApplicationId        string   `protobuf:"bytes,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

func (m *ReportRequest) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *ReportRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReportRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReportReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=gateway.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportReply) Reset()         { *m = ReportReply{} }
func (m *ReportReply) String() string { return proto.CompactTextString(m) }
func (*ReportReply) ProtoMessage()    {}
func (*ReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportReply.Unmarshal(m, b)
}
func (m *ReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportReply.Marshal(b, m, deterministic)
}
func (m *ReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportReply.Merge(m, src)
}
func (m *ReportReply) XXX_Size() int {
	return xxx_messageInfo_ReportReply.Size(m)
}
func (m *ReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReportReply proto.InternalMessageInfo

func (m *ReportReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Success
}

func (m *ReportReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginRequest struct {
	LoginId              string   `protobuf:"bytes,1,opt,name=loginId,proto3" json:"loginId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ApplicationId        string   `protobuf:"bytes,3,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	IpAddress            string   `protobuf:"bytes,4,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *LoginRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type LoginReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=gateway.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Expire               int64    `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Success
}

func (m *LoginReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReply) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func init() {
	proto.RegisterEnum("gateway.Status", Status_name, Status_value)
	proto.RegisterType((*ReportRequest)(nil), "gateway.ReportRequest")
	proto.RegisterType((*ReportReply)(nil), "gateway.ReportReply")
	proto.RegisterType((*LoginRequest)(nil), "gateway.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "gateway.LoginReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x9b, 0xfe, 0x49, 0xbe, 0xde, 0xb6, 0x9f, 0x65, 0xac, 0x25, 0x14, 0x17, 0x25, 0x08,
	0x16, 0x17, 0x15, 0x2a, 0x82, 0x5b, 0x97, 0x82, 0x0b, 0x99, 0xfa, 0x02, 0x63, 0x72, 0x2d, 0x83,
	0x69, 0x67, 0xcc, 0x9d, 0x58, 0x23, 0xb8, 0xf7, 0xb1, 0x25, 0x93, 0xa4, 0x5a, 0xab, 0xb8, 0x71,
	0x97, 0x73, 0x4e, 0x92, 0x39, 0xbf, 0xb9, 0x17, 0x7a, 0x84, 0xc9, 0x93, 0x0c, 0x71, 0xaa, 0x13,
	0x65, 0x14, 0xf3, 0x16, 0xc2, 0xe0, 0x5a, 0x64, 0x41, 0x06, 0x3d, 0x8e, 0x5a, 0x25, 0x86, 0xe3,
	0x63, 0x8a, 0x64, 0x98, 0x0f, 0x5e, 0xac, 0x16, 0x72, 0x75, 0x15, 0xf9, 0xce, 0xd8, 0x99, 0xb4,
	0x79, 0x25, 0xd9, 0x11, 0xf4, 0x84, 0xd6, 0xb1, 0x0c, 0x85, 0x91, 0x2a, 0xcf, 0xeb, 0x36, 0xdf,
	0x36, 0xd9, 0x00, 0x5a, 0x46, 0x3d, 0xe0, 0xca, 0x6f, 0xd8, 0xb4, 0x10, 0x8c, 0x41, 0x33, 0x12,
	0x46, 0xf8, 0xcd, 0xb1, 0x33, 0xe9, 0x72, 0xfb, 0x1c, 0xdc, 0x40, 0xa7, 0x3a, 0x5a, 0xc7, 0x19,
	0x3b, 0x06, 0x97, 0x8c, 0x30, 0x29, 0xd9, 0x73, 0xff, 0xcf, 0xf6, 0xa6, 0x65, 0xc7, 0xe9, 0xdc,
	0xda, 0xbc, 0x8c, 0xf3, 0x86, 0x4b, 0x24, 0x12, 0x0b, 0x2c, 0x1b, 0x54, 0x32, 0x78, 0x73, 0xa0,
	0x7b, 0x9d, 0xb7, 0xfd, 0x1d, 0x66, 0x04, 0xff, 0xb4, 0x20, 0x5a, 0xab, 0xa4, 0xe2, 0xd8, 0xe8,
	0x5d, 0xd0, 0xc6, 0x77, 0xa0, 0x87, 0xd0, 0x96, 0xfa, 0x32, 0x8a, 0x12, 0x24, 0xb2, 0x5c, 0x6d,
	0xfe, 0x61, 0x04, 0xaf, 0x00, 0x65, 0x93, 0xbf, 0x61, 0xfb, 0xe1, 0x5e, 0x87, 0xe0, 0xe2, 0xb3,
	0x96, 0x09, 0xda, 0x06, 0x0d, 0x5e, 0xaa, 0x93, 0x53, 0x70, 0x8b, 0x3f, 0xb3, 0x0e, 0x78, 0xf3,
	0x34, 0x0c, 0x91, 0xa8, 0x5f, 0xcb, 0x05, 0xc7, 0xfb, 0x94, 0x30, 0xea, 0x3b, 0xb9, 0xb8, 0x95,
	0x4b, 0x54, 0xa9, 0xe9, 0xd7, 0x67, 0x2f, 0xe0, 0xcd, 0x8b, 0x0d, 0x61, 0x17, 0xe0, 0x16, 0x73,
	0x61, 0xc3, 0x4d, 0xcd, 0xad, 0x1d, 0x19, 0x0d, 0x76, 0x7c, 0x1d, 0x67, 0x41, 0x8d, 0x9d, 0x43,
	0xcb, 0x42, 0xb3, 0x83, 0xcd, 0x0b, 0x9f, 0xc7, 0x31, 0xda, 0xff, 0x6a, 0xdb, 0xcf, 0xee, 0x5c,
	0xbb, 0x93, 0x67, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xce, 0x06, 0x64, 0xa4, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportReply, error) {
	out := new(ReportReply)
	err := c.cc.Invoke(ctx, "/gateway.Service/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/gateway.Service/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Report(context.Context, *ReportRequest) (*ReportReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Report(ctx context.Context, req *ReportRequest) (*ReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (*UnimplementedServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Service/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Service/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Service_Report_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Service_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
